apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stable-diffusion-hpa
spec:
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: kubernetes.io|container|accelerator|duty_cycle
          selector:
            matchLabels:
              resource.labels.namespace_name: $namespace
        target:
          type: AverageValue
          averageValue: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "stable-diffusion-deployment"